import type { Metadata } from "next";
import "./global.css";
import "./custom.css"
import Link from "next/link";
import Navigation from "@/components/custom/Navigation";
import Header from "@/components/custom/Header";

export const metadata: Metadata = {
  title: "Market Place",
  description: "Generated by litakk",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Header />

        <div className="main-container relative h-screen w-full">
          <nav>
          </nav>
          {children}

          <div className="fixed bottom-0 left-0 w-full">
            <Navigation />
          </div>

        </div>
      </body>

    </html >
  );
}
